-- 15
create table if not exists customer
(
    code    integer generated by default as identity,
    name    varchar not null,
    address varchar not null,
    constraint pk_code primary key (code)
);

-- 14
create table if not exists finished_products_shipment
(
    warehouse_num            integer not null,
    shipment_document_number integer not null,
    customer_code            integer not null,
    finished_product_code    integer not null,
    unit_of_measurement      varchar,
    quantity                 integer check ( quantity > 0 ),
    shipment_date            date default now(),
    constraint pk_shipment primary key (warehouse_num, shipment_document_number),
    constraint fk_customer foreign key (customer_code) references customer (code)
        on delete cascade on update cascade
);

-- 16в
create table if not exists products_availability
(
    warehouse_num       integer not null,
    product_code        integer not null,
    unit_of_measurement varchar not null,
    amount_left         integer check ( amount_left > 0 ),
    last_operation_date date default now(),
    constraint pk_availability primary key (warehouse_num, product_code)
);

insert into customer (name, address)
values ('Artem', 'Moscow'),
       ('Ivan', 'Kazan'),
       ('Petr', 'Omsk'),
       ('Eugene', 'Kirov'),
       ('Oleg', 'Saratov');

insert into finished_products_shipment
(warehouse_num, shipment_document_number, customer_code, finished_product_code, unit_of_measurement, quantity,
 shipment_date)
values (1, 1, 1, 1, 'cm', 3, '2022-01-03'::date),
       (2, 2, 2, 2, 'litres', 2, '2022-02-13'::date),
       (3, 3, 4, 3, 'm', 6, '2022-04-10'::date),
       (4, 4, 5, 4, 'cm', 2, '2022-05-07'::date),
       (5, 5, 3, 5, 'm', 10, '2022-11-14'::date);

insert into products_availability
(warehouse_num, product_code, unit_of_measurement, amount_left, last_operation_date)
values (1, 1, 'cm', 3, '2022-01-03'::date),
       (2, 2, 'litres', 2, '2022-02-13'::date),
       (3, 3, 'm', 6, '2022-04-10'::date),
       (4, 4, 'cm', 2, '2022-05-07'::date),
       (5, 5, 'm', 10, '2022-11-14'::date);
